services:
  sorbate.discordbot:
    image: sorbate.discordbot
    build:
      context: .
      dockerfile: Sorbate.DiscordBot/Dockerfile
    volumes:
      - app-data:/app

volumes:
  app-data:
  sorbate:
    image: sorbate
    build:
      context: .
      dockerfile: Sorbate/Dockerfile
