services:
  sorbate:
    image: sorbate
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Sorbate/Dockerfile
    depends_on:
      - db
    environment:
      Discord__AuthToken: ${DISCORD_TOKEN}
      ConnectionStrings__DefaultConnection: Host=db;Database=postgres;Username=postgres;Password=${DB_PASSWORD}
    env_file:
      - path: .env
        required: true
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - path: .env
        required: true
    ports:
      - 5432:5432