services:
  sorbate.discordbot:
    image: sorbate.discordbot
    build:
      context: .
      dockerfile: Sorbate.DiscordBot/Dockerfile

  sorbate.storage:
    image: sorbate.storage
    build:
      context: .
      dockerfile: Sorbate.Storage/Dockerfile
